[profile.default]
src = "contracts"
out = "out"
libs = [
    "lib",
    "node_modules",
]
remappings = [
    "@ensdomains/=node_modules/@ensdomains/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "forge-std/=lib/forge-std/src/",
    "hardhat/=node_modules/hardhat/",
    "truffle/=node_modules/truffle/",
]

ffi = true

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
mainnet = "https://mainnet.infura.io/v3/${INFURA_TOKEN}"
goerli = "https://goerli.infura.io/v3/${INFURA_TOKEN}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_TOKEN}"
polygon_pos = "https://polygon-mainnet.infura.io/v3/${INFURA_TOKEN}"
mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_TOKEN}"
polygon_zkevm = "https://zkevm-rpc.com"
polygon_zkevm_testnet = "https://rpc.public.zkevm-test.net"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
